build-by-default: true
branches:
  - main
projects:
  TradeGui:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.2.0
